<?php

/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div class="feature-content-container" id="my_feature_content">
    <div class="my-feature-banner">
       <p class="banner-style">
           <?php echo __('Do you need a custom feature?', 'aam'); ?>
           <a href="https://github.com/wpaam/AAM-Feature-Example" target="_blank">
           <?php echo __('Create your own extension ', 'aam'); ?>
           </a> <?php echo __('or ask us and we will develop it for you.', 'aam'); ?>
       </p> 
    </div>
</div>