<h2>AAM Development Framework</h2>

<p>
    Are you passionate about WordPress development? We are too! Become a member of 
    the AAM community and obtain our 
    <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3Q6UDARTR532U" target="_blank">Exclusive Development License</a> 
    where you can profit from your own ideas and have access to all AAM extensions.
</p>

<p>
    We receive regular requests and suggestions for new extensions and decided we would 
    extend the opportunity to  create and earn  by opening our platform to you. We will 
    host your extensions on our server so you may develop custom features for you and 
    your customers. If you have a great idea and would like to create an extension for 
    sales, we will review, approve and host it on AAM server.
</p>

<p>
    You can download the sample extension from our official 
    <a href="https://github.com/wpaam/AAM-Feature-Example" target="_blank">GitHub Repository</a> 
    and customize it to your special need.
</p>

<p>
    Additionally the 
    <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3Q6UDARTR532U" target="_blank">AAM Development License</a> 
    gives you an opportunity to download <b>ALL</b> AAM extensions that are available 
    now and all new extensions that will be developed within a year from the time of purchase.
</p>