<h2>AAM Extensions</h2>

<p>
    Advanced Access Manager is free platform and you can use most of the features without
    any limitations but in case you are looking for more, this is where AAM extensions
    might be useful for you to check. Complete list of available extensions you can find 
    on AAM->Extensions page.
</p>
<p>
    We are using PayPal to process the payment and if it completed successfully, you will
    automatically receive an email with license key that you can use to activate the extension.
</p>
<p>
    In case of any issues with license key, we guaranty to resolve the issue within one business day.
    Otherwise your money back.
</p>