<h2>Frequently Asked Questions</h2>

<h4>What is Advanced Access Manager?</h4>
<p>
    Advanced Access Manager (aka AAM) is free WordPress plugin that allows you to 
    control access to your website. With AAM you can manager access to your Posts, 
    Pages and Categories, filter unnecessary areas in your Backend, manager Users and
    Roles and many more. 
</p>

<h4>What should I know to understand how AAM works?</h4>
<p>
    Best way to learn more about AAM is to check our 
    <a href="http://wpaam.com/tutorials/" target="_blank">collection of tutorials</a>.
    From here you'll get the basic understanding about most important aspects of AAM
    functionality. It is also very important to understand how WordPress 
    <a href="https://codex.wordpress.org/Roles_and_Capabilities" target="_blank">Roles & Capabilities</a> 
    are organized.
</p>

<h4>I'm not able to manage Administrator Role. What am I missing?</h4>
<p>
    In fact that AAM is very powerful tool, many unexperienced users were able to limit 
    Administrator rights and loose access to Dashboard. That is why from AAM Release 2.5 
    we introduced <a href="http://wpaam.com/tutorials/aam-super-admin/" target="_blank">AAM Super Admin</a>.
    You can make one user in your system as AAM Super Administrator that is able to manager other
    administrators.<br/>
    <span style="color:#FF0000; font-weight: bold;">Warning!</span> Do not limit capabilities for Administrator
    Role, because even if you are AAM Super Administrator, you still remain WordPress Administrator.
</p>

<h4>What is ConfigPress?</h4>
<p>
    Think about ConfigPress as a settings page but instead of dozens of checkboxes, drop-downs and input fields 
    you use configuration script based on <a href="http://en.wikipedia.org/wiki/INI_file" target="_blank">INI Standard</a>. 
    The reason we use this format is that AAM is not only just a plugin but complex and very flexible development 
    tool. That is why we came to conclusion to organize all settings in ConfigPress format. 
</p>