<h2>General Overview</h2>
<p>
    Advanced Access Manager (aka AAM) is one of the most popular access control plugins. It is easy-to-use but
    at the same time very powerful tool that gives you a flexible control over your either
    single WordPress site or Multisite Network. With AAM you are allowed to configure access
    to different parts of your website for any <i>role</i> or individual <i>user</i>.
</p>
<p>
    Another great aspect of AAM is that our team constantly working on new features and improving
    existing. We are very dedicated to success of this project and our support is ready to help you
    within 48hours.
</p>
<p>
    Below you can find some of the major feature that are available in current AAM version:
</p>

<b>Control access to backend menu (including submenu).</b> As example you can restrict 
access for <i>role</i> Editor to Menu "Pages" or does not allow any <i>user</i> to 
manage Post's Categories.<br/>
<br/>
<b>Filter <i>widgets</i> & <i>metaboxes</i>.</b> Filter the list of metaboxes that any <i>role</i> 
or <i>user</i> can see during Post/Page editing. At the same time you can filter the 
list of Dashboard and Frontend widgets.<br/>
<br/>
<b>Control access to any <i>post</i>, <i>page</i>, <i>custom post type</i> or <i>category</i>.</b> 
You can restrict access to page or post for any <i>user</i> or <i>role</i> as well as
restrict access to entire <i>category</i> and all posts inside it. You can also restrict 
commenting for pages or exclude any from the frontend menu. For more restrictions you can 
consider to get <a href="http://wpaam.com/aam-extensions/aam-plus-package/" target="_blank">AAM Plus Package</a>.<br/>
<br/>
<b>Filter Post or Page content.</b> You can filter Post's or Page's content for 
currently logged in user or visitor. This feature is available with extension 
<a href="http://wpaam.com/aam-extensions/aam-content-filter/" target="_blank">AAM Content Manager</a>.<br/>
<br/>
<b>Manage capabilities for any <i>role</i> or <i>user</i>.</b> 
AAM, with simple interface, allows you to grand or remove capabilities for any <i>role</i> or <i>user</i>.
You can also create new custom capability or remove existing.<br/>
<br/>
<b>Create custom actions for system events.</b> As example your system can send email 
to you if some user published post or page, or modified content. You also can develop 
your own custom action for system event.<br/>
<br/>
<b>Track <i>user</i> activities.</b> With AAM you can track user activities within 
your website. So you can easily find out when user was logged in or modified any post 
or page. To extend the list of tracked activities, consider to get 
<a href="http://wpaam.com/aam-extensions/aam-activities/" target="_blank">AAM Activities</a> 
extension.

