<?php

/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div class="feature-content-container" id="metabox_content">
    <div class="metabox-top-actions">
        <div class="metabox-top-action-link">
            <input type="text" class="link-text" id="metabox_link" />
        </div>
        <a href="#" class="aam-icon aam-icon-medium aam-icon-medium-add" id="retrieve_url" aam-tooltip="<?php echo __('Retrieve Metaboxes From Link', 'aam') ;?>"><span></span></a>
        <a href="#" class="aam-icon aam-icon-medium aam-icon-medium-refresh" id="refresh_metaboxes" aam-tooltip="<?php echo __('Refresh the List', 'aam') ;?>"><span></span></a>
        <br class="clear" />
    </div>
    <div class="aam-metabox-loader"></div>
    <div id="metabox_list_container"></div>
</div>